services:
  postgres:
    container_name: stocks-postgres
    image: postgres:latest
    env_file: ".env"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - stocks-net

volumes:
  postgres_data:

networks:
  stocks-net:
    driver: bridge
