services:
  postgres:
    container_name: stocks-postgres
    image: postgres:17.4
    env_file: ".env"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - stocks-net
  
  redis:
    container_name: stocks-redis
    image: redis:7.4.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - stocks-net

  api:
    build: .
    container_name: stocks-api
    image: stocks-api:latest
    env_file: ".env"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - stocks-net
    restart: always

volumes:
  postgres_data:
  redis_data:

networks:
  stocks-net:
    driver: bridge
